id: ad83a0f95d49419296bef4e3032da88a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_309-The_Sutra_on_Impermanence-v1
  language: en
  author: ''
  volume: {}
